# $FreeBSD$

PORTNAME=	grafana2
PORTVERSION=	2.5.0
DISTVERSIONPREFIX=	v
CATEGORIES=	www

MAINTAINER=	thomas@bartelmess.io
COMMENT=	Dashboard and graph editor for Graphite, InfluxDB & OpenTSDB

LICENSE=	APACHE20

BUILD_DEPENDS=	${LOCALBASE}/bin/go:${PORTSDIR}/lang/go

ONLY_FOR_ARCHS=	i386 amd64

USE_RC_SUBR=	grafana

USES=	compiler

PRECOMPILED_CSS_JS_DESC=	Use pre-generated web assets
COMPILE_JS_CSS_DESC=	Generate web assets

OPTIONS_SINGLE=	ASSESTS
OPTIONS_SINGLE_ASSESTS=	PRECOMPILED_CSS_JS COMPILE_JS_CSS
OPTIONS_DEFAULT=	PRECOMPILED_CSS_JS

USE_GITHUB=	yes
{{gh_accounts}}
{{gh_projects}}
{{gh_tags}}

GRAFANA_USER?=	grafana
GRAFANA_GROUP?=	grafana

USERS=	${GRAFANA_USER}
GROUPS=	${GRAFANA_GROUP}

GRAFANAHOMEDIR=	${PREFIX}/share/grafana/
GRAFANADATADIR=	/var/db/${PORTNAME}/
GRAFANALOGDIR=	/var/log/${PORTNAME}/
GRAFANAPIDDIR=	/var/run/${PORTNAME}/

SUB_FILES=	grafana grafana.conf
SUB_LIST+=	GRAFANA_USER=${GRAFANA_USER} \
	GRAFANA_GROUP=${GRAFANA_GROUP} \
	GRAFANADATADIR=${GRAFANADATADIR} \
	GRAFANALOGDIR=${GRAFANALOGDIR} \
	GRAFANAPIDDIR=${GRAFANAPIDDIR} \
	GRAFANAHOMEDIR=${GRAFANAHOMEDIR}

PLIST_SUB+=	GRAFANAHOMEDIR=${GRAFANAHOMEDIR}

.include <bsd.port.options.mk>

.if ${PORT_OPTIONS:MPRECOMPILED_CSS_JS}
MASTER_SITES+=	http://files.bartelmess.io/public/:static_assets
DISTFILES+=	grafana-static-${PORTVERSION}.tar.gz:static_assets
.endif

.if ${PORT_OPTIONS:MCOMPILE_JS_CSS}
BUILD_DEPENDS+= npm>=0:${PORTSDIR}/www/npm
.endif
post-extract:
	@${MKDIR} ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana
.for src in .bra.toml .jscs.json CHANGELOG.md Gruntfile.js README.md build.go docker main.go pkg tasks \
	.gitignore .jsfmtrc CONTRIBUTING.md LICENSE.md appveyor.yml circle.yml docs package.json public tests \
	.hooks .jshintrc Godeps NOTICE.md benchmarks conf latest.json packaging vendor
	@${MV} ${WRKSRC}/${src} \
	${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana
.endfor
{% for dep in deps %}	@${MKDIR} ${WRKSRC}/src/{{dep.project_path}}
{% endfor %}
{% for dep in deps %}	@${MV} ${WRKSRC_{{dep.name}}} ${WRKSRC}/src/{{dep.dependency_path}}
{% endfor %}
.if ${PORT_OPTIONS:MPRECOMPILED_CSS_JS}
	@${RM} -rf ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana/public
	@${MV} ${WRKDIR}/public  ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana/
.endif

do-build:
	@cd ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana; \
	${SETENV} ${BUILD_ENV} GOPATH=${WRKSRC} go run build.go build

.if ${PORT_OPTIONS:MCOMPILE_JS_CSS}
	cd ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana; npm install
	cd ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana; \
	${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana/node_modules/grunt-cli/bin/grunt
.endif

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana/bin/grafana-server \
	${STAGEDIR}${PREFIX}/bin/grafana-server
	@cd ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana && \
	${COPYTREE_SHARE} public ${STAGEDIR}${PREFIX}/share/grafana
	@${MKDIR} ${STAGEDIR}${GRAFANAPIDDIR}
	@${MKDIR} ${STAGEDIR}${GRAFANALOGDIR}
	@${MKDIR} ${STAGEDIR}${GRAFANAHOMEDIR}
	@${MKDIR} ${STAGEDIR}${GRAFANADATADIR}
	@${MKDIR} ${STAGEDIR}${GRAFANAHOMEDIR}/conf
	${INSTALL_DATA} ${WRKSRC}/src/github.com/${GH_ACCOUNT}/grafana/conf/defaults.ini \
	${STAGEDIR}${GRAFANAHOMEDIR}/conf/defaults.ini
	${INSTALL_DATA} ${WRKDIR}/grafana.conf ${STAGEDIR}${PREFIX}/etc/grafana.conf

.include <bsd.port.pre.mk>

.if ${OPSYS} == FreeBSD && ${OSVERSION} < 900044 && ${ARCH} == i386
BROKEN= Does not build
.endif

# golang assumes that if clang is in use, it is called "clang" and not "cc". If
# it's called "cc", go fails.
.if ${COMPILER_TYPE} == clang
BUILD_ENV=	CC=clang
.endif

.include <bsd.port.post.mk>
